# Spring properties
spring:
  application:
     name: microservice-greeting  # El servicio se registra con este nombre
  freemarker:
    enabled: false           # Ingnora las plantillas de Freemaker para el dashboard de Eureka
  thymeleaf:
    cache: false             # PErmite que las plantillas de Thymeleaf sean recargadas en tiempo de ejecución
    prefix: classpath:/templates/    # Trailing / mandatory
                             # Template location for this application only
 
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
 
# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port