spring:
    application:
        name: customer-client-service
    freemaker:
        enable: false
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
error:
    path=/error

eureka: 
    client: 
        serviceUrl: 
            defaultZone: http://localhost:1111/eureka/

server:
    port: 3333